/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DomainContactsV2 struct {
	Registrant *ContactDomain `json:"registrant,omitempty"`
	Admin *ContactDomain `json:"admin,omitempty"`
	Tech *ContactDomain `json:"tech,omitempty"`
	Billing *ContactDomain `json:"billing,omitempty"`
}
