/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActionReason struct {
	// Short identifier, suitable for indicating the reason for the current status and how to handle within client code
	Code string `json:"code"`
	// Human-readable, English description of the code
	Message string `json:"message,omitempty"`
	// List of the specific fields, and the errors found with their contents
	Fields []ErrorField `json:"fields,omitempty"`
}
