/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MaintenanceDetail struct {
	// Date and time (UTC) when this maintenance was created
	CreatedAt string `json:"createdAt"`
	// Date and time (UTC) when this maintenance will complete
	EndsAt string `json:"endsAt"`
	// The environment on which the maintenance will be performed<br/><ul><li><strong style='margin-left: 12px;'>OTE</strong> - The Operational Testing Environment.</li><li><strong style='margin-left: 12px;'>PRODUCTION</strong> - The Live Production Environment.</li></ul>
	Environment string `json:"environment"`
	// The identifier for the system maintenance
	MaintenanceId string `json:"maintenanceId"`
	// Date and time (UTC) when this maintenance was last modified
	ModifiedAt string `json:"modifiedAt"`
	// The reason for the maintenance being performed<br/><ul><li><strong style='margin-left: 12px;'>EMERGENCY</strong> - Unexpected Emergency maintenance.</li><li><strong style='margin-left: 12px;'>PLANNED</strong> - Planned system maintenance.</li></ul>
	Reason string `json:"reason"`
	// Date and time (UTC) when this maintenance will start
	StartsAt string `json:"startsAt"`
	// The status of maintenance<br/><ul><li><strong style='margin-left: 12px;'>ACTIVE</strong> - The upcoming maintenance is active.</li><li><strong style='margin-left: 12px;'>CANCELLED</strong> - The upcoming maintenance has been cancelled.</li></ul>
	Status string `json:"status"`
	// A brief description of what is being performed
	Summary string `json:"summary"`
	// List of systems that are impacted by the maintenance.
	Systems []MaintenanceSystem `json:"systems,omitempty"`
	// List of tlds that are in maintenance.  Generally only applies when `type` is REGISTRY
	Tlds []string `json:"tlds,omitempty"`
	// The type of maintenance being performed<br/><ul><li><strong style='margin-left: 12px;'>API</strong> - Programmatic Api components.</li><li><strong style='margin-left: 12px;'>REGISTRY</strong> - The underlying Registry providing the tld(s).</li><li><strong style='margin-left: 12px;'>UI</strong> - User Interface components.</li></ul>
	Type_ string `json:"type"`
}
