/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RenewalDetails struct {
	// Whether or not the domain is eligble for renewal based on status
	Renewable bool `json:"renewable,omitempty"`
	// Price for the domain renewal excluding taxes or fees
	Price int32 `json:"price"`
	// Currency in which the `price` is listed
	Currency string `json:"currency"`
}
