/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DomainNotificationType struct {
	// The notification type
	Type_ string `json:"type"`
}
