/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConsentRedemption struct {
	// Price for the domain renewal (if domain renewal required for redemption). Please use GET /v2/customers/{customerId}/domains/{domain} to retrieve the redemption price and currency for the domain
	Price int32 `json:"price"`
	// Fee charged for the domain redemption. Please use GET /v2/customers/{customerId}/domains/{domain} to retrieve the redemption fee and currency for the domain
	Fee int32 `json:"fee"`
	// Currency in which the `price` and `fee` are listed
	Currency string `json:"currency"`
	// Originating client IP address of the end-user's computer when they consented to these legal agreements
	AgreedBy string `json:"agreedBy"`
	// Timestamp indicating when the end-user consented to these legal agreements
	AgreedAt string `json:"agreedAt"`
}
