/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DomainTransferIn struct {
	// Authorization code from registrar for transferring a domain
	AuthCode string `json:"authCode"`
	Consent *Consent `json:"consent"`
	// Can be more than 1 but no more than 10 years total including current registration length
	Period int32 `json:"period,omitempty"`
	// Whether or not privacy has been requested
	Privacy bool `json:"privacy,omitempty"`
	// Whether or not the domain should be configured to automatically renew
	RenewAuto bool `json:"renewAuto,omitempty"`
	ContactAdmin *Contact `json:"contactAdmin,omitempty"`
	ContactBilling *Contact `json:"contactBilling,omitempty"`
	ContactRegistrant *Contact `json:"contactRegistrant,omitempty"`
	ContactTech *Contact `json:"contactTech,omitempty"`
}
