/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VerificationsDomain struct {
	DomainName *VerificationDomainName `json:"domainName,omitempty"`
	RealName *VerificationRealName `json:"realName,omitempty"`
}
