---
name: build on push dev

on:
  schedule:
    - cron: "44 4 * * *"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O swagger_domains.json https://developer.godaddy.com/swagger/swagger_domains.json
      - name: check md5 swagger file
        run: |

          if [[ -f swagger_domains.json.md5 && $(cat swagger_domains.json.md5) == $(md5sum swagger_domains.json | awk '{print $1}') ]]; then echo "Swagger File is unchanged; exit 1" ; else md5sum swagger_domains.json | awk '{print $1}' > swagger_domains.json.md5 ; fi
      - name: Swagger Codegen v3
        uses: bjerkio/swagger-codegen-action@v1
        with:
          args: |
            generate --lang go --input-spec swagger_domains.json --http-user-agent 'Godaddy-Client/golang'
      - name: change authorization
        run: |
          sudo chmod -R 777 *
          sudo chmod -R 777 .swagger-codegen
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update godaddy-domains
          title: Update godaddy-domains
          body: |
            Update godaddy-domains
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: swagger-codegen
